# Generated by Django 5.2.1 on 2025-06-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_alter_destination_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCiudad', models.CharField(help_text='Ej: Machu Picchu, Lima, Arequipa', max_length=100, verbose_name='Nombre de la Ciudad')),
                ('imagenCiudad', models.ImageField(help_text='Sube una foto representativa', upload_to='destinos_peru', verbose_name='Imagen del Destino')),
                ('descripcionCiudad', models.TextField(help_text='Detalles históricos, culturales o turísticos', verbose_name='Descripción')),
                ('precioTour', models.IntegerField(help_text='Precio en soles peruanos', verbose_name='Precio del Tour (S/.)')),
                ('ofertaTour', models.BooleanField(default=False, help_text='Marcar si está en promoción', verbose_name='¿En oferta?')),
            ],
            options={
                'verbose_name': 'Destino Turístico',
                'verbose_name_plural': 'Destinos Turísticos',
            },
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
