# Generated by Django 5.2.1 on 2025-06-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_destinoturistico_delete_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinoturistico',
            name='precioTour',
            field=models.IntegerField(help_text='Precio en soles peruanos', verbose_name='Precio del Tour (S/)'),
        ),
    ]
