# Generated by Django 5.2.2 on 2025-06-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_character_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='movies',
            field=models.ManyToManyField(to='events.movie'),
        ),
    ]
