# Generated by Django 5.2.1 on 2025-06-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinosturisticos',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='destinosturisticos',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Vistas'),
        ),
    ]
